# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Xiao Xiao
subtitle: 打不死的小强 ~
description: 记录生活点滴，留存过往记忆
keywords: [前端面试题, 小草无根, 花开无心, 落叶无根]
author: Xiao Xiao
language: zh-cn
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://daijc.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: material-x

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:daijc/daijc.github.io.git
  branch: master
#avatar
avatar: "http://pdliii7ak.bkt.clouddn.com/photo2.jpg"
#recommended_posts
recommended_posts:
  enabled: true

# valine评论
valine:
  enable: true;
  appId:  "bEFytQ4Rpyo4jzlqfudykpsp-gzGzoHsz"
  appKey:  "9TNjGhdqST9S4QB3yieeAeEC"
  guest_info: nick,mail
  placeholder: 快来评论吧~
  avatar: mp
  pageSize: 10
  verify: false
  notify: false
  lang: zh-cn